version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
  backend:
    build: ./backend
    restart: always
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
    depends_on:
      - backend
      - frontend
      - db

